// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("F# extensions for CNTK")>]
[<assembly: AssemblyProductAttribute("CNTK.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("F# extensions to simplify CNTK usage")>]
[<assembly: AssemblyVersionAttribute("0.1.4")>]
[<assembly: AssemblyFileVersionAttribute("0.1.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "F# extensions for CNTK"
    let [<Literal>] AssemblyProduct = "CNTK.FSharp"
    let [<Literal>] AssemblyDescription = "F# extensions to simplify CNTK usage"
    let [<Literal>] AssemblyVersion = "0.1.4"
    let [<Literal>] AssemblyFileVersion = "0.1.4"
